import { Character } from './types';

export const CHARACTERS: Character[] = [
  {
    id: 'gojo',
    name: 'Satoru Gojo',
    japaneseName: '五条 悟',
    domainName: 'Unlimited Void',
    domainNameKanji: '無量空処',
    color: 'bg-blue-950',
    accentColor: 'text-cyan-400',
    description: 'The strongest sorcerer.',
    handSignDescription: '【單手判定】唯一使用單手的角色。右手食指與中指交叉（帝釋天印）。',
    imagePrompt: '',
    videoPrompt: '',
    placeholderImage: ''
  },
  {
    id: 'sukuna',
    name: 'Ryomen Sukuna',
    japaneseName: '両面 宿儺',
    domainName: 'Malevolent Shrine',
    domainNameKanji: '伏魔御廚子',
    color: 'bg-red-950',
    accentColor: 'text-red-500',
    description: 'King of Curses.',
    handSignDescription: '【雙手接觸】必須有「菱形開口」。手指交扣，掌心中央留出明顯空洞。',
    imagePrompt: '',
    videoPrompt: '',
    placeholderImage: ''
  },
  {
    id: 'megumi',
    name: 'Megumi Fushiguro',
    japaneseName: '伏黒 恵',
    domainName: 'Chimera Shadow Garden',
    domainNameKanji: '嵌合暗翳庭',
    color: 'bg-emerald-950',
    accentColor: 'text-emerald-400',
    description: 'Ten Shadows User.',
    handSignDescription: '【腹部手勢】正確位置為腹部前。手指交織如影繪（影子戲），關鍵是兩個大拇指明顯「指向前方/對手」，而非藏起。',
    imagePrompt: '',
    videoPrompt: '',
    placeholderImage: ''
  },
  {
    id: 'mahito',
    name: 'Mahito',
    japaneseName: '真人',
    domainName: 'Self-Embodiment of Perfection',
    domainNameKanji: '自閉円頓裹',
    color: 'bg-gray-900',
    accentColor: 'text-purple-400',
    description: 'Cursed Spirit.',
    handSignDescription: '【表情判定】特徵是「張大嘴巴」。模仿領域展開時口中出現手臂的形態。無需特定手勢，嘴巴張大即可觸發。',
    imagePrompt: '',
    videoPrompt: '',
    placeholderImage: ''
  },
  {
    id: 'jogo',
    name: 'Jogo',
    japaneseName: '漏瑚',
    domainName: 'Coffin of the Iron Mountain',
    domainNameKanji: '蓋棺鉄囲山',
    color: 'bg-orange-950',
    accentColor: 'text-orange-500',
    description: 'Cursed Spirit of Fire.',
    handSignDescription: '【雙手接觸】特徵是「實心岩石」。雙手死鎖成球狀，手指不突出，整體圓潤。大拇指通常向上或內扣，不指向前方。',
    imagePrompt: '',
    videoPrompt: '',
    placeholderImage: ''
  },
  {
    id: 'hakari',
    name: 'Kinji Hakari',
    japaneseName: '秤 金次',
    domainName: 'Idle Death Gamble',
    domainNameKanji: '坐殺博徒',
    color: 'bg-yellow-950',
    accentColor: 'text-yellow-400',
    description: 'The Gambler.',
    handSignDescription: '【雙手分離】特徵是「圓環」。雙手分開，拇指與食指捏合成圈（OK手勢）。',
    imagePrompt: '',
    videoPrompt: '',
    placeholderImage: ''
  },
  {
    id: 'yuta',
    name: 'Yuta Okkotsu',
    japaneseName: '乙骨 憂太',
    domainName: 'Authentic Mutual Love',
    domainNameKanji: '真贋相愛',
    color: 'bg-slate-900',
    accentColor: 'text-pink-400',
    description: 'Special Grade Sorcerer.',
    handSignDescription: '【雙手分離】特徵是「前後交疊」。雙手不接觸，一前一後（景深不同）。手掌面向胸口。',
    imagePrompt: '',
    videoPrompt: '',
    placeholderImage: ''
  },
  {
    id: 'mahoraga',
    name: 'Divine General Mahoraga',
    japaneseName: '魔虚羅',
    domainName: 'Eight-Handled Sword',
    domainNameKanji: '布留部由良由良',
    color: 'bg-neutral-300',
    accentColor: 'text-yellow-600',
    description: 'The Divergent Sila.',
    handSignDescription: '【隱藏術式】雙拳相對，模擬轉動法輪之姿。',
    imagePrompt: '',
    videoPrompt: '',
    placeholderImage: '',
    hidden: true
  }
];